using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace SheetSetEditor.Services;

public enum AppLanguage { Dutch, English, German, French, Afrikaans, Frisian, Klingon }

public sealed class LocalizationService : INotifyPropertyChanged
{
    public static readonly LocalizationService Instance = new();
    private LocalizationService() { }

    private AppLanguage _language = AppLanguage.Dutch;
    private Dictionary<string, string> _dict = Strings.Dutch;

    public AppLanguage Language
    {
        get => _language;
        set
        {
            _language = value;
            _dict = value switch
            {
                AppLanguage.English   => Strings.English,
                AppLanguage.German    => Strings.German,
                AppLanguage.French    => Strings.French,
                AppLanguage.Afrikaans => Strings.Afrikaans,
                AppLanguage.Frisian   => Strings.Frisian,
                AppLanguage.Klingon   => Strings.Klingon,
                _                    => Strings.Dutch,
            };
            // Notify all indexed bindings
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs("Item[]"));
            OnPropertyChanged();
        }
    }

    public string this[string key] => _dict.TryGetValue(key, out var v) ? v : $"[{key}]";

    public static string T(string key) => Instance[key];

    public event PropertyChangedEventHandler? PropertyChanged;
    private void OnPropertyChanged([CallerMemberName] string? name = null)
        => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));
}

// ─── String dictionaries per language ─────────────────────────────────────────

internal static class Strings
{
    internal static readonly Dictionary<string, string> Dutch = new()
    {
        // Common actions
        ["Apply"]         = "Toepassen",
        ["Save"]          = "Opslaan",
        ["Cancel"]        = "Annuleren",
        ["OK"]            = "OK",
        ["Yes"]           = "Ja",
        ["No"]            = "Nee",
        ["Delete"]        = "Verwijderen",
        ["Undo"]          = "Ongedaan maken",
        ["Close"]         = "Sluiten",
        ["Browse"]        = "Bladeren…",
        ["Add"]           = "Toevoegen",
        ["Edit"]          = "Bewerken",
        ["Rename"]        = "Hernaam…",
        ["Back"]          = "← Terug",
        ["Next"]          = "Volgende →",
        ["Finish"]        = "Voltooien",

        // File menu
        ["FileMenu"]        = "Geen bestand ▼",
        ["Open"]            = "Openen…",
        ["New"]             = "Nieuwe sheet set…",
        ["ImportCsv"]       = "CSV/TSV importeren…",
        ["ExportCsv"]       = "Exporteer naar CSV…",
        ["UndoImport"]      = "Ongedaan maken (import)",
        ["RecentFiles"]     = "Recente bestanden",
        ["Options"]         = "Opties…",

        // Main window
        ["AutoNumber"]       = "AutoNummer",
        ["StartNumber"]      = "Start nummer:",
        ["NoSelection"]      = "Geen selectie",
        ["SheetNumber"]      = "Bladnummer:",
        ["Title"]            = "Titel:",
        ["Description"]      = "Omschrijving:",
        ["Layout"]           = "Layout:",
        ["DwgFile"]          = "Bestand:",
        ["RevisionNumber"]   = "Revisienummer:",
        ["RevisionDate"]     = "Revisiedatum:",
        ["IssuePurpose"]     = "Uitgiftedoel:",
        ["Category"]         = "Categorie:",
        ["DoNotPlot"]        = "Niet plotten:",
        ["CustomProperties"] = "Custom properties",
        ["AddNewProperty"]   = "+ Nieuwe property",
        ["SheetSetFields"]   = "Sheetset velden",
        ["SheetFields"]      = "Blad velden (standaard beginwaarden)",
        ["SubsetName"]       = "Naam:",
        ["Property"]         = "Property",
        ["Value"]            = "Waarde",
        ["DefaultValue"]     = "Standaard waarde",
        ["OtherFields"]      = "Overige standaardvelden",
        ["MainFields"]       = "Hoofdvelden",
        ["Subset"]           = "Subset",

        // Confirmations
        ["SureTitle"]               = "Weet u het zeker?",
        ["DeleteSubsetConfirm"]     = "Subset verwijderen?",
        ["DeleteSheetConfirm"]      = "Blad verwijderen?",
        ["DeletePropertyConfirm"]   = "Property \"{0}\" verwijderen?",
        ["DeletePropertyWithVals"]  = "Property \"{0}\" verwijderen?\nDit verwijdert ook alle bladwaarden voor dit veld.",
        ["OverwriteProfileConfirm"] = "Profiel \"{0}\" bestaat al. Overschrijven?",
        ["UndoImportConfirm"]       = "Import van \"{0}\" ({1:HH:mm:ss}) ongedaan maken?",

        // Import wizard
        ["ImportTitle"]     = "Importeren",
        ["Step1"]           = "Stap 1 van 4: Bestand(en) kiezen",
        ["Step2"]           = "Stap 2 van 4: Koppelen",
        ["Step3"]           = "Stap 3 van 4: Voorbeeld",
        ["Step4"]           = "Stap 4 van 4: Resultaat",
        ["ImportFile"]      = "Importbestand:",
        ["AllSheets"]       = "Alle sheets",
        ["SelectedSheets"]  = "Geselecteerde sheets",
        ["PickSheets"]      = "Kies sheets…",
        ["ApplyTo"]         = "Pas toe op:",
        ["Profile"]         = "Profiel:",
        ["LoadProfile"]     = "Laad profiel",
        ["SaveProfile"]     = "Sla op als profiel…",
        ["DeleteProfile"]   = "× Verwijder",
        ["AutoMap"]         = "Auto-koppelen op naam",
        ["SplitField"]      = "✂ Splits",
        ["Separator"]       = "Scheidingsteken:",
        ["PreviewExample"]  = "Voorbeeld (eerste bestand):",
        ["TargetProperty"]  = "Sheet Set property",
        ["SourceField"]     = "Veld",
        ["ExampleValue"]    = "Voorbeeld",

        // Options
        ["OptionsTitle"]    = "Opties",
        ["Language"]        = "Taal",
        ["Theme"]           = "Thema",
        ["LightMode"]       = "Licht",
        ["DarkMode"]        = "Donker",
        ["Appearance"]      = "Weergave",
        ["General"]         = "Algemeen",
        ["AutoBackup"]      = "Automatische back-up bij opslaan",
        ["RecentFilesCount"]= "Maximaal aantal recente bestanden",

        // Status
        ["Ready"]           = "Gereed",
        ["Saved"]           = "Opgeslagen.",
        ["UndoDone"]        = "Ongedaan gemaakt.",
        ["ImportDone"]      = "Import klaar",
        ["UndoDeleteDone"]  = "Verwijdering van '{0}' ongedaan gemaakt.",
        ["UndoDeleteBtn"]   = "↩ Ongedaan",
    };

    internal static readonly Dictionary<string, string> English = new()
    {
        ["Apply"]         = "Apply",
        ["Save"]          = "Save",
        ["Cancel"]        = "Cancel",
        ["OK"]            = "OK",
        ["Yes"]           = "Yes",
        ["No"]            = "No",
        ["Delete"]        = "Delete",
        ["Undo"]          = "Undo",
        ["Close"]         = "Close",
        ["Browse"]        = "Browse…",
        ["Add"]           = "Add",
        ["Edit"]          = "Edit",
        ["Rename"]        = "Rename…",
        ["Back"]          = "← Back",
        ["Next"]          = "Next →",
        ["Finish"]        = "Finish",

        ["FileMenu"]        = "No file ▼",
        ["Open"]            = "Open…",
        ["New"]             = "New sheet set…",
        ["ImportCsv"]       = "Import CSV/TSV…",
        ["ExportCsv"]       = "Export to CSV…",
        ["UndoImport"]      = "Undo import",
        ["RecentFiles"]     = "Recent files",
        ["Options"]         = "Options…",

        ["AutoNumber"]       = "AutoNumber",
        ["StartNumber"]      = "Start number:",
        ["NoSelection"]      = "No selection",
        ["SheetNumber"]      = "Sheet number:",
        ["Title"]            = "Title:",
        ["Description"]      = "Description:",
        ["Layout"]           = "Layout:",
        ["DwgFile"]          = "File:",
        ["RevisionNumber"]   = "Revision number:",
        ["RevisionDate"]     = "Revision date:",
        ["IssuePurpose"]     = "Issue purpose:",
        ["Category"]         = "Category:",
        ["DoNotPlot"]        = "Do not plot:",
        ["CustomProperties"] = "Custom properties",
        ["AddNewProperty"]   = "+ New property",
        ["SheetSetFields"]   = "Sheet set fields",
        ["SheetFields"]      = "Sheet fields (default values)",
        ["SubsetName"]       = "Name:",
        ["Property"]         = "Property",
        ["Value"]            = "Value",
        ["DefaultValue"]     = "Default value",
        ["OtherFields"]      = "Other standard fields",
        ["MainFields"]       = "Main fields",
        ["Subset"]           = "Subset",

        ["SureTitle"]               = "Are you sure?",
        ["DeleteSubsetConfirm"]     = "Delete subset?",
        ["DeleteSheetConfirm"]      = "Delete sheet?",
        ["DeletePropertyConfirm"]   = "Delete property \"{0}\"?",
        ["DeletePropertyWithVals"]  = "Delete property \"{0}\"?\nThis also removes all per-sheet values.",
        ["OverwriteProfileConfirm"] = "Profile \"{0}\" already exists. Overwrite?",
        ["UndoImportConfirm"]       = "Undo import of \"{0}\" ({1:HH:mm:ss})?",

        ["ImportTitle"]     = "Import",
        ["Step1"]           = "Step 1 of 4: Choose file",
        ["Step2"]           = "Step 2 of 4: Map fields",
        ["Step3"]           = "Step 3 of 4: Preview",
        ["Step4"]           = "Step 4 of 4: Result",
        ["ImportFile"]      = "Import file:",
        ["AllSheets"]       = "All sheets",
        ["SelectedSheets"]  = "Selected sheets",
        ["PickSheets"]      = "Pick sheets…",
        ["ApplyTo"]         = "Apply to:",
        ["Profile"]         = "Profile:",
        ["LoadProfile"]     = "Load profile",
        ["SaveProfile"]     = "Save as profile…",
        ["DeleteProfile"]   = "× Remove",
        ["AutoMap"]         = "Auto-map by name",
        ["SplitField"]      = "✂ Split",
        ["Separator"]       = "Separator:",
        ["PreviewExample"]  = "Preview (first file):",
        ["TargetProperty"]  = "Sheet Set property",
        ["SourceField"]     = "Field",
        ["ExampleValue"]    = "Example",

        ["OptionsTitle"]    = "Options",
        ["Language"]        = "Language",
        ["Theme"]           = "Theme",
        ["LightMode"]       = "Light",
        ["DarkMode"]        = "Dark",
        ["Appearance"]      = "Appearance",
        ["General"]         = "General",
        ["AutoBackup"]      = "Auto-backup on save",
        ["RecentFilesCount"]= "Maximum recent files",

        ["Ready"]           = "Ready",
        ["Saved"]           = "Saved.",
        ["UndoDone"]        = "Undone.",
        ["ImportDone"]      = "Import complete",
        ["UndoDeleteDone"]  = "Deletion of '{0}' undone.",
        ["UndoDeleteBtn"]   = "↩ Undo",
    };

    internal static readonly Dictionary<string, string> German = new()
    {
        ["Apply"]         = "Anwenden",
        ["Save"]          = "Speichern",
        ["Cancel"]        = "Abbrechen",
        ["OK"]            = "OK",
        ["Yes"]           = "Ja",
        ["No"]            = "Nein",
        ["Delete"]        = "Löschen",
        ["Undo"]          = "Rückgängig",
        ["Close"]         = "Schließen",
        ["Browse"]        = "Durchsuchen…",
        ["Add"]           = "Hinzufügen",
        ["Edit"]          = "Bearbeiten",
        ["Rename"]        = "Umbenennen…",
        ["Back"]          = "← Zurück",
        ["Next"]          = "Weiter →",
        ["Finish"]        = "Fertigstellen",

        ["FileMenu"]        = "Keine Datei ▼",
        ["Open"]            = "Öffnen…",
        ["New"]             = "Neues Blattset…",
        ["ImportCsv"]       = "CSV/TSV importieren…",
        ["ExportCsv"]       = "Als CSV exportieren…",
        ["UndoImport"]      = "Import rückgängig",
        ["RecentFiles"]     = "Zuletzt geöffnet",
        ["Options"]         = "Einstellungen…",

        ["AutoNumber"]       = "AutoNummerierung",
        ["StartNumber"]      = "Startnummer:",
        ["NoSelection"]      = "Keine Auswahl",
        ["SheetNumber"]      = "Blattnummer:",
        ["Title"]            = "Titel:",
        ["Description"]      = "Beschreibung:",
        ["Layout"]           = "Layout:",
        ["DwgFile"]          = "Datei:",
        ["RevisionNumber"]   = "Revisionsnummer:",
        ["RevisionDate"]     = "Revisionsdatum:",
        ["IssuePurpose"]     = "Ausgabezweck:",
        ["Category"]         = "Kategorie:",
        ["DoNotPlot"]        = "Nicht plotten:",
        ["CustomProperties"] = "Benutzerdefinierte Eigenschaften",
        ["AddNewProperty"]   = "+ Neue Eigenschaft",
        ["SheetSetFields"]   = "Blattset-Felder",
        ["SheetFields"]      = "Blattfelder (Standardwerte)",
        ["SubsetName"]       = "Name:",
        ["Property"]         = "Eigenschaft",
        ["Value"]            = "Wert",
        ["DefaultValue"]     = "Standardwert",
        ["OtherFields"]      = "Weitere Standardfelder",
        ["MainFields"]       = "Hauptfelder",
        ["Subset"]           = "Teilmenge",

        ["SureTitle"]               = "Sind Sie sicher?",
        ["DeleteSubsetConfirm"]     = "Teilmenge löschen?",
        ["DeleteSheetConfirm"]      = "Blatt löschen?",
        ["DeletePropertyConfirm"]   = "Eigenschaft \"{0}\" löschen?",
        ["DeletePropertyWithVals"]  = "Eigenschaft \"{0}\" löschen?\nDies entfernt auch alle blatteigenen Werte.",
        ["OverwriteProfileConfirm"] = "Profil \"{0}\" existiert bereits. Überschreiben?",
        ["UndoImportConfirm"]       = "Import von \"{0}\" ({1:HH:mm:ss}) rückgängig machen?",

        ["ImportTitle"]     = "Importieren",
        ["Step1"]           = "Schritt 1 von 4: Datei wählen",
        ["Step2"]           = "Schritt 2 von 4: Felder zuordnen",
        ["Step3"]           = "Schritt 3 von 4: Vorschau",
        ["Step4"]           = "Schritt 4 von 4: Ergebnis",
        ["ImportFile"]      = "Importdatei:",
        ["AllSheets"]       = "Alle Blätter",
        ["SelectedSheets"]  = "Ausgewählte Blätter",
        ["PickSheets"]      = "Blätter wählen…",
        ["ApplyTo"]         = "Anwenden auf:",
        ["Profile"]         = "Profil:",
        ["LoadProfile"]     = "Profil laden",
        ["SaveProfile"]     = "Als Profil speichern…",
        ["DeleteProfile"]   = "× Entfernen",
        ["AutoMap"]         = "Auto-Zuordnung nach Name",
        ["SplitField"]      = "✂ Teilen",
        ["Separator"]       = "Trennzeichen:",
        ["PreviewExample"]  = "Vorschau (erste Datei):",
        ["TargetProperty"]  = "Blattset-Eigenschaft",
        ["SourceField"]     = "Feld",
        ["ExampleValue"]    = "Beispiel",

        ["OptionsTitle"]    = "Einstellungen",
        ["Language"]        = "Sprache",
        ["Theme"]           = "Design",
        ["LightMode"]       = "Hell",
        ["DarkMode"]        = "Dunkel",
        ["Appearance"]      = "Darstellung",
        ["General"]         = "Allgemein",
        ["AutoBackup"]      = "Automatisches Backup beim Speichern",
        ["RecentFilesCount"]= "Maximale Anzahl zuletzt geöffneter Dateien",

        ["Ready"]           = "Bereit",
        ["Saved"]           = "Gespeichert.",
        ["UndoDone"]        = "Rückgängig gemacht.",
        ["ImportDone"]      = "Import abgeschlossen",
        ["UndoDeleteDone"]  = "Löschung von '{0}' rückgängig gemacht.",
        ["UndoDeleteBtn"]   = "↩ Rückgängig",
    };

    internal static readonly Dictionary<string, string> French = new()
    {
        ["Apply"]         = "Appliquer",
        ["Save"]          = "Enregistrer",
        ["Cancel"]        = "Annuler",
        ["OK"]            = "OK",
        ["Yes"]           = "Oui",
        ["No"]            = "Non",
        ["Delete"]        = "Supprimer",
        ["Undo"]          = "Annuler l'action",
        ["Close"]         = "Fermer",
        ["Browse"]        = "Parcourir…",
        ["Add"]           = "Ajouter",
        ["Edit"]          = "Modifier",
        ["Rename"]        = "Renommer…",
        ["Back"]          = "← Retour",
        ["Next"]          = "Suivant →",
        ["Finish"]        = "Terminer",

        ["FileMenu"]        = "Aucun fichier ▼",
        ["Open"]            = "Ouvrir…",
        ["New"]             = "Nouveau jeu de feuilles…",
        ["ImportCsv"]       = "Importer CSV/TSV…",
        ["ExportCsv"]       = "Exporter en CSV…",
        ["UndoImport"]      = "Annuler l'import",
        ["RecentFiles"]     = "Fichiers récents",
        ["Options"]         = "Options…",

        ["AutoNumber"]       = "Numérotation auto",
        ["StartNumber"]      = "Numéro de départ :",
        ["NoSelection"]      = "Aucune sélection",
        ["SheetNumber"]      = "Numéro de feuille :",
        ["Title"]            = "Titre :",
        ["Description"]      = "Description :",
        ["Layout"]           = "Présentation :",
        ["DwgFile"]          = "Fichier :",
        ["RevisionNumber"]   = "N° de révision :",
        ["RevisionDate"]     = "Date de révision :",
        ["IssuePurpose"]     = "Objet d'émission :",
        ["Category"]         = "Catégorie :",
        ["DoNotPlot"]        = "Ne pas tracer :",
        ["CustomProperties"] = "Propriétés personnalisées",
        ["AddNewProperty"]   = "+ Nouvelle propriété",
        ["SheetSetFields"]   = "Champs du jeu de feuilles",
        ["SheetFields"]      = "Champs de feuille (valeurs par défaut)",
        ["SubsetName"]       = "Nom :",
        ["Property"]         = "Propriété",
        ["Value"]            = "Valeur",
        ["DefaultValue"]     = "Valeur par défaut",
        ["OtherFields"]      = "Autres champs standard",
        ["MainFields"]       = "Champs principaux",
        ["Subset"]           = "Sous-ensemble",

        ["SureTitle"]               = "Êtes-vous sûr ?",
        ["DeleteSubsetConfirm"]     = "Supprimer le sous-ensemble ?",
        ["DeleteSheetConfirm"]      = "Supprimer la feuille ?",
        ["DeletePropertyConfirm"]   = "Supprimer la propriété « {0} » ?",
        ["DeletePropertyWithVals"]  = "Supprimer la propriété « {0} » ?\nCela supprime aussi toutes les valeurs par feuille.",
        ["OverwriteProfileConfirm"] = "Le profil « {0} » existe déjà. Écraser ?",
        ["UndoImportConfirm"]       = "Annuler l'import de « {0} » ({1:HH:mm:ss}) ?",

        ["ImportTitle"]     = "Importer",
        ["Step1"]           = "Étape 1 sur 4 : Choisir un fichier",
        ["Step2"]           = "Étape 2 sur 4 : Mapper les champs",
        ["Step3"]           = "Étape 3 sur 4 : Aperçu",
        ["Step4"]           = "Étape 4 sur 4 : Résultat",
        ["ImportFile"]      = "Fichier d'import :",
        ["AllSheets"]       = "Toutes les feuilles",
        ["SelectedSheets"]  = "Feuilles sélectionnées",
        ["PickSheets"]      = "Choisir des feuilles…",
        ["ApplyTo"]         = "Appliquer à :",
        ["Profile"]         = "Profil :",
        ["LoadProfile"]     = "Charger le profil",
        ["SaveProfile"]     = "Enregistrer comme profil…",
        ["DeleteProfile"]   = "× Supprimer",
        ["AutoMap"]         = "Mappage automatique par nom",
        ["SplitField"]      = "✂ Diviser",
        ["Separator"]       = "Séparateur :",
        ["PreviewExample"]  = "Aperçu (premier fichier) :",
        ["TargetProperty"]  = "Propriété du jeu de feuilles",
        ["SourceField"]     = "Champ",
        ["ExampleValue"]    = "Exemple",

        ["OptionsTitle"]    = "Options",
        ["Language"]        = "Langue",
        ["Theme"]           = "Thème",
        ["LightMode"]       = "Clair",
        ["DarkMode"]        = "Sombre",
        ["Appearance"]      = "Apparence",
        ["General"]         = "Général",
        ["AutoBackup"]      = "Sauvegarde auto à l'enregistrement",
        ["RecentFilesCount"]= "Nombre maximum de fichiers récents",

        ["Ready"]           = "Prêt",
        ["Saved"]           = "Enregistré.",
        ["UndoDone"]        = "Action annulée.",
        ["ImportDone"]      = "Import terminé",
        ["UndoDeleteDone"]  = "Suppression de « {0} » annulée.",
        ["UndoDeleteBtn"]   = "↩ Annuler",
    };

    internal static readonly Dictionary<string, string> Afrikaans = new()
    {
        ["Apply"]         = "Toepas",
        ["Save"]          = "Stoor",
        ["Cancel"]        = "Kanselleer",
        ["OK"]            = "OK",
        ["Yes"]           = "Ja",
        ["No"]            = "Nee",
        ["Delete"]        = "Verwyder",
        ["Undo"]          = "Ontdoen",
        ["Close"]         = "Sluit",
        ["Browse"]        = "Blaai…",
        ["Add"]           = "Voeg by",
        ["Edit"]          = "Wysig",
        ["Rename"]        = "Hernoem…",
        ["Back"]          = "← Terug",
        ["Next"]          = "Volgende →",
        ["Finish"]        = "Voltooi",

        ["FileMenu"]        = "Geen lêer ▼",
        ["Open"]            = "Maak oop…",
        ["New"]             = "Nuwe blaatstel…",
        ["ImportCsv"]       = "Voer CSV/TSV in…",
        ["ExportCsv"]       = "Voer uit na CSV…",
        ["UndoImport"]      = "Ontdoen invoer",
        ["RecentFiles"]     = "Onlangse lêers",
        ["Options"]         = "Opsies…",

        ["AutoNumber"]       = "OutoNommering",
        ["StartNumber"]      = "Beginommer:",
        ["NoSelection"]      = "Geen keuse",
        ["SheetNumber"]      = "Blaatommer:",
        ["Title"]            = "Titel:",
        ["Description"]      = "Beskrywing:",
        ["Layout"]           = "Uitleg:",
        ["DwgFile"]          = "Lêer:",
        ["RevisionNumber"]   = "Hersieningsnommer:",
        ["RevisionDate"]     = "Hersieningsdatum:",
        ["IssuePurpose"]     = "Uitreikdoel:",
        ["Category"]         = "Kategorie:",
        ["DoNotPlot"]        = "Moenie plot nie:",
        ["CustomProperties"] = "Gepasmaakte eienskappe",
        ["AddNewProperty"]   = "+ Nuwe eienskap",
        ["SheetSetFields"]   = "Blaatstel velde",
        ["SheetFields"]      = "Blaatvelde (verstekwaardes)",
        ["SubsetName"]       = "Naam:",
        ["Property"]         = "Eienskap",
        ["Value"]            = "Waarde",
        ["DefaultValue"]     = "Verstekwaarde",
        ["OtherFields"]      = "Ander standaardvelde",
        ["MainFields"]       = "Hoofvelde",
        ["Subset"]           = "Deelstel",

        ["SureTitle"]               = "Is u seker?",
        ["DeleteSubsetConfirm"]     = "Deelstel verwyder?",
        ["DeleteSheetConfirm"]      = "Blaat verwyder?",
        ["DeletePropertyConfirm"]   = "Eienskap \"{0}\" verwyder?",
        ["DeletePropertyWithVals"]  = "Eienskap \"{0}\" verwyder?\nDit verwyder ook alle blaatspesifieke waardes.",
        ["OverwriteProfileConfirm"] = "Profiel \"{0}\" bestaan reeds. Oorskryf?",
        ["UndoImportConfirm"]       = "Invoer van \"{0}\" ({1:HH:mm:ss}) ontdoen?",

        ["ImportTitle"]     = "Invoer",
        ["Step1"]           = "Stap 1 van 4: Kies lêer",
        ["Step2"]           = "Stap 2 van 4: Koppel velde",
        ["Step3"]           = "Stap 3 van 4: Voorskou",
        ["Step4"]           = "Stap 4 van 4: Resultaat",
        ["ImportFile"]      = "Invoerlêer:",
        ["AllSheets"]       = "Alle blaate",
        ["SelectedSheets"]  = "Gekose blaate",
        ["PickSheets"]      = "Kies blaate…",
        ["ApplyTo"]         = "Pas toe op:",
        ["Profile"]         = "Profiel:",
        ["LoadProfile"]     = "Laai profiel",
        ["SaveProfile"]     = "Stoor as profiel…",
        ["DeleteProfile"]   = "× Verwyder",
        ["AutoMap"]         = "Outo-koppeling op naam",
        ["SplitField"]      = "✂ Verdeel",
        ["Separator"]       = "Skeier:",
        ["PreviewExample"]  = "Voorskou (eerste lêer):",
        ["TargetProperty"]  = "Blaatstel eienskap",
        ["SourceField"]     = "Veld",
        ["ExampleValue"]    = "Voorbeeld",

        ["OptionsTitle"]    = "Opsies",
        ["Language"]        = "Taal",
        ["Theme"]           = "Tema",
        ["LightMode"]       = "Lig",
        ["DarkMode"]        = "Donker",
        ["Appearance"]      = "Voorkoms",
        ["General"]         = "Algemeen",
        ["AutoBackup"]      = "Outomatiese rugsteun by stoor",
        ["RecentFilesCount"]= "Maksimum onlangse lêers",

        ["Ready"]           = "Gereed",
        ["Saved"]           = "Gestoor.",
        ["UndoDone"]        = "Ontdoen.",
        ["ImportDone"]      = "Invoer klaar",
        ["UndoDeleteDone"]  = "Verwydering van '{0}' ontdoen.",
        ["UndoDeleteBtn"]   = "↩ Ontdoen",
    };

    internal static readonly Dictionary<string, string> Frisian = new()
    {
        ["Apply"]         = "Tapasse",
        ["Save"]          = "Bewarje",
        ["Cancel"]        = "Annulearje",
        ["OK"]            = "OK",
        ["Yes"]           = "Ja",
        ["No"]            = "Nee",
        ["Delete"]        = "Fuortsmite",
        ["Undo"]          = "Ungedien meitsje",
        ["Close"]         = "Slute",
        ["Browse"]        = "Blêdzje…",
        ["Add"]           = "Tafoegje",
        ["Edit"]          = "Bewurkje",
        ["Rename"]        = "Omneame…",
        ["Back"]          = "← Werom",
        ["Next"]          = "Folgjende →",
        ["Finish"]        = "Ôfrûnje",

        ["FileMenu"]        = "Gjin triem ▼",
        ["Open"]            = "Iepenje…",
        ["New"]             = "Nij blêdeset…",
        ["ImportCsv"]       = "CSV/TSV ymportearje…",
        ["ExportCsv"]       = "Eksportearje nei CSV…",
        ["UndoImport"]      = "Ymport ungedien meitsje",
        ["RecentFiles"]     = "Resinte triemmen",
        ["Options"]         = "Opsjes…",

        ["AutoNumber"]       = "AutoNûmmerjen",
        ["StartNumber"]      = "Startnûmer:",
        ["NoSelection"]      = "Gjin seleksje",
        ["SheetNumber"]      = "Blêdenûmer:",
        ["Title"]            = "Titel:",
        ["Description"]      = "Beskriuwing:",
        ["Layout"]           = "Lay-out:",
        ["DwgFile"]          = "Triem:",
        ["RevisionNumber"]   = "Revisjenûmer:",
        ["RevisionDate"]     = "Revisjedatum:",
        ["IssuePurpose"]     = "Útjefdoel:",
        ["Category"]         = "Kategory:",
        ["DoNotPlot"]        = "Net plotte:",
        ["CustomProperties"] = "Oanpaste eigenskippen",
        ["AddNewProperty"]   = "+ Nije eigenskip",
        ["SheetSetFields"]   = "Blêdeset fjilden",
        ["SheetFields"]      = "Blêdfjilden (standertwearden)",
        ["SubsetName"]       = "Namme:",
        ["Property"]         = "Eigenskip",
        ["Value"]            = "Wearde",
        ["DefaultValue"]     = "Standertwearde",
        ["OtherFields"]      = "Oare standertfjilden",
        ["MainFields"]       = "Haadfjilden",
        ["Subset"]           = "Dielset",

        ["SureTitle"]               = "Binne jo wis?",
        ["DeleteSubsetConfirm"]     = "Dielset fuortsmite?",
        ["DeleteSheetConfirm"]      = "Blêd fuortsmite?",
        ["DeletePropertyConfirm"]   = "Eigenskip \"{0}\" fuortsmite?",
        ["DeletePropertyWithVals"]  = "Eigenskip \"{0}\" fuortsmite?\nDit smyt ek alle blêdwearden fuort.",
        ["OverwriteProfileConfirm"] = "Profyl \"{0}\" bestiet al. Oerskriuwe?",
        ["UndoImportConfirm"]       = "Ymport fan \"{0}\" ({1:HH:mm:ss}) ungedien meitsje?",

        ["ImportTitle"]     = "Ymportearje",
        ["Step1"]           = "Stap 1 fan 4: Triem kieze",
        ["Step2"]           = "Stap 2 fan 4: Fjilden keppelje",
        ["Step3"]           = "Stap 3 fan 4: Foarbyld",
        ["Step4"]           = "Stap 4 fan 4: Resultaat",
        ["ImportFile"]      = "Ymporttriem:",
        ["AllSheets"]       = "Alle blêden",
        ["SelectedSheets"]  = "Selektearre blêden",
        ["PickSheets"]      = "Blêden kieze…",
        ["ApplyTo"]         = "Tapasse op:",
        ["Profile"]         = "Profyl:",
        ["LoadProfile"]     = "Profyl lade",
        ["SaveProfile"]     = "Bewarje as profyl…",
        ["DeleteProfile"]   = "× Fuortsmite",
        ["AutoMap"]         = "Auto-keppelje op namme",
        ["SplitField"]      = "✂ Splitsen",
        ["Separator"]       = "Skiedingteken:",
        ["PreviewExample"]  = "Foarbyld (earste triem):",
        ["TargetProperty"]  = "Blêdeset eigenskip",
        ["SourceField"]     = "Fjild",
        ["ExampleValue"]    = "Foarbyld",

        ["OptionsTitle"]    = "Opsjes",
        ["Language"]        = "Taal",
        ["Theme"]           = "Tema",
        ["LightMode"]       = "Ljocht",
        ["DarkMode"]        = "Tsjuster",
        ["Appearance"]      = "Uterlik",
        ["General"]         = "Algemien",
        ["AutoBackup"]      = "Automatyske reservekopy by bewarjen",
        ["RecentFilesCount"]= "Maksimum resinte triemmen",

        ["Ready"]           = "Klear",
        ["Saved"]           = "Bewarre.",
        ["UndoDone"]        = "Ungedien makke.",
        ["ImportDone"]      = "Ymport klear",
        ["UndoDeleteDone"]  = "Fuortsmiten fan '{0}' ungedien makke.",
        ["UndoDeleteBtn"]   = "↩ Ungedien",
    };

    internal static readonly Dictionary<string, string> Klingon = new()
    {
        ["Apply"]         = "lI'moH",
        ["Save"]          = "toD",
        ["Cancel"]        = "Qaw'",
        ["OK"]            = "HIja'",
        ["Yes"]           = "HIja'",
        ["No"]            = "ghobe'",
        ["Delete"]        = "teq",
        ["Undo"]          = "nID qa'",
        ["Close"]         = "SoQmoH",
        ["Browse"]        = "nejmoH…",
        ["Add"]           = "boq",
        ["Edit"]          = "choH",
        ["Rename"]        = "pong choH…",
        ["Back"]          = "← tlhej",
        ["Next"]          = "qen →",
        ["Finish"]        = "rIn",

        ["FileMenu"]        = "nav Hutlh ▼",
        ["Open"]            = "poSmoH…",
        ["New"]             = "chu' nav tetlh…",
        ["ImportCsv"]       = "CSV/TSV tlhej…",
        ["ExportCsv"]       = "CSV ngeH…",
        ["UndoImport"]      = "tlhej nID qa'",
        ["RecentFiles"]     = "qen nav",
        ["Options"]         = "De'mey…",

        ["AutoNumber"]       = "mI' QaD",
        ["StartNumber"]      = "mI' taH:",
        ["NoSelection"]      = "wIv Hutlh",
        ["SheetNumber"]      = "nav mI':",
        ["Title"]            = "pong:",
        ["Description"]      = "QIjmeH:",
        ["Layout"]           = "qeS:",
        ["DwgFile"]          = "nav:",
        ["RevisionNumber"]   = "choH mI':",
        ["RevisionDate"]     = "choH jaj:",
        ["IssuePurpose"]     = "ngeH meq:",
        ["Category"]         = "ghItlh:",
        ["DoNotPlot"]        = "tuj Hutlh:",
        ["CustomProperties"] = "De' tIng",
        ["AddNewProperty"]   = "+ chu' De'",
        ["SheetSetFields"]   = "nav tetlh yotlh",
        ["SheetFields"]      = "nav yotlh (motlh De')",
        ["SubsetName"]       = "pong:",
        ["Property"]         = "De'",
        ["Value"]            = "mI'",
        ["DefaultValue"]     = "motlh mI'",
        ["OtherFields"]      = "latlh motlh yotlh",
        ["MainFields"]       = "wa'DIch yotlh",
        ["Subset"]           = "nav'a' tlhoy",

        ["SureTitle"]               = "DaHarlaH'a'?",
        ["DeleteSubsetConfirm"]     = "nav'a' tlhoy teq?",
        ["DeleteSheetConfirm"]      = "nav teq?",
        ["DeletePropertyConfirm"]   = "De' \"{0}\" teq?",
        ["DeletePropertyWithVals"]  = "De' \"{0}\" teq?\nnav De' je teq.",
        ["OverwriteProfileConfirm"] = "SeH \"{0}\" taH. chu'Ha'moH?",
        ["UndoImportConfirm"]       = "tlhej \"{0}\" ({1:HH:mm:ss}) nID qa'?",

        ["ImportTitle"]     = "tlhej",
        ["Step1"]           = "mI' 1/4: nav wIv",
        ["Step2"]           = "mI' 2/4: yotlh boq",
        ["Step3"]           = "mI' 3/4: legh",
        ["Step4"]           = "mI' 4/4: mIw rIn",
        ["ImportFile"]      = "tlhej nav:",
        ["AllSheets"]       = "Hoch nav",
        ["SelectedSheets"]  = "wIvta' nav",
        ["PickSheets"]      = "nav wIv…",
        ["ApplyTo"]         = "lI'moH:",
        ["Profile"]         = "SeH:",
        ["LoadProfile"]     = "SeH nap",
        ["SaveProfile"]     = "SeH toD…",
        ["DeleteProfile"]   = "× teq",
        ["AutoMap"]         = "QaD pong boq",
        ["SplitField"]      = "✂ ghargh",
        ["Separator"]       = "bIng:",
        ["PreviewExample"]  = "legh (wa' nav):",
        ["TargetProperty"]  = "nav tetlh De'",
        ["SourceField"]     = "yotlh",
        ["ExampleValue"]    = "leghmeH",

        ["OptionsTitle"]    = "De'mey",
        ["Language"]        = "Hol",
        ["Theme"]           = "rItlh",
        ["LightMode"]       = "wov",
        ["DarkMode"]        = "Hurgh",
        ["Appearance"]      = "leghmeH",
        ["General"]         = "motlh",
        ["AutoBackup"]      = "QaD toD toD-taH",
        ["RecentFilesCount"]= "law' qen nav",

        ["Ready"]           = "DaH",
        ["Saved"]           = "toDta'.",
        ["UndoDone"]        = "nID qa'ta'.",
        ["ImportDone"]      = "tlhej rIn",
        ["UndoDeleteDone"]  = "'{0}' teq nID qa'.",
        ["UndoDeleteBtn"]   = "↩ nID qa'",
    };

    internal static Dictionary<string, string> GetDictionary(AppLanguage lang) => lang switch
    {
        AppLanguage.English   => English,
        AppLanguage.German    => German,
        AppLanguage.French    => French,
        AppLanguage.Afrikaans => Afrikaans,
        AppLanguage.Frisian   => Frisian,
        AppLanguage.Klingon   => Klingon,
        _                    => Dutch,
    };
}
