// ACSMCOMPONENTS24Lib
// 
// Types:
// 
// AcSmAcDbBlockRecordReference
// AcSmAcDbBlockRecordReferenceClass
// AcSmAcDbDatabase
// AcSmAcDbDatabaseClass
// AcSmAcDbLayoutReference
// AcSmAcDbLayoutReferenceClass
// AcSmAcDbObjectReference
// AcSmAcDbObjectReferenceClass
// AcSmAcDbViewReference
// AcSmAcDbViewReferenceClass
// AcSmCalloutBlockReferences
// AcSmCalloutBlockReferencesClass
// AcSmCalloutBlocks
// AcSmCalloutBlocksClass
// AcSmCustomPropertyBag
// AcSmCustomPropertyBagClass
// AcSmCustomPropertyValue
// AcSmCustomPropertyValueClass
// AcSmDatabase
// AcSmDatabaseClass
// AcSmDSTFiler
// AcSmDSTFilerClass
// AcSmEvent
// AcSmFileReference
// AcSmFileReferenceClass
// AcSmFileWatchReactor
// AcSmFileWatchReactorClass
// AcSmLockStatus
// AcSmNamedAcDbObjectReference
// AcSmNamedAcDbObjectReferenceClass
// AcSmObjectReference
// AcSmObjectReferenceClass
// AcSmObjectReferenceFlags
// AcSmPersistImpl
// AcSmPersistImplClass
// AcSmPersistProxy
// AcSmPersistProxyClass
// AcSmProjectPointLocation
// AcSmProjectPointLocationClass
// AcSmProjectPointLocations
// AcSmProjectPointLocationsClass
// AcSmPublishOptions
// AcSmPublishOptionsClass
// AcSmResources
// AcSmResourcesClass
// AcSmSheet
// AcSmSheetClass
// AcSmSheetSelSet
// AcSmSheetSelSetClass
// AcSmSheetSelSets
// AcSmSheetSelSetsClass
// AcSmSheetSet
// AcSmSheetSetClass
// AcSmSheetSetMgr
// AcSmSheetSetMgrClass
// AcSmSheetView
// AcSmSheetViewClass
// AcSmSheetViews
// AcSmSheetViewsClass
// AcSmSimpleFileReference
// AcSmSimpleFileReferenceClass
// AcSmSubset
// AcSmSubsetClass
// AcSmViewCategories
// AcSmViewCategoriesClass
// AcSmViewCategory
// AcSmViewCategoryClass
// FileNotifyAction
// FileNotifyFlags
// IAcSmAcDbBlockRecordReference
// IAcSmAcDbDatabase
// IAcSmAcDbLayoutReference
// IAcSmAcDbObjectReference
// IAcSmAcDbViewReference
// IAcSmCalloutBlocks
// IAcSmComponent
// IAcSmCustomPropertyBag
// IAcSmCustomPropertyValue
// IAcSmDatabase
// IAcSmDatabase_Internal
// IAcSmDatabase_Internal2
// IAcSmEnumAcDbBlockRecordReference
// IAcSmEnumComponent
// IAcSmEnumDatabase
// IAcSmEnumFileReference
// IAcSmEnumPersist
// IAcSmEnumProjectPointLocation
// IAcSmEnumProperty
// IAcSmEnumSheetSelSet
// IAcSmEnumSheetView
// IAcSmEnumViewCategory
// IAcSmEvents
// IAcSmFiler
// IAcSmFileReference
// IAcSmFileReference_Internal
// IAcSmFiler_Internal
// IAcSmFileWatchReactor
// IAcSmNamedAcDbObjectReference
// IAcSmObjectId
// IAcSmObjectReference
// IAcSmPersist
// IAcSmPersistImpl_Internal
// IAcSmPersistProxy
// IAcSmProjectPointLocation
// IAcSmProjectPointLocation2
// IAcSmProjectPointLocations
// IAcSmPublishOptions
// IAcSmPublishOptions2
// IAcSmPublishOptions3
// IAcSmPublishOptions4
// IAcSmResources
// IAcSmSheet
// IAcSmSheet2
// IAcSmSheetSelSet
// IAcSmSheetSelSets
// IAcSmSheetSet
// IAcSmSheetSet2
// IAcSmSheetSetMgr
// IAcSmSheetSetMgr_Internal
// IAcSmSheetView
// IAcSmSheetViews
// IAcSmSheetView_Internal
// IAcSmSubset
// IAcSmSubset2
// IAcSmViewCategories
// IAcSmViewCategory
// IAdComFileWatchReactor
// INameValueMap_Internal
// NameValueMap
// NameValueMapClass
// PropertyFlags
// __MIDL___MIDL_itf_AcSmComponents_0000_0009_0001
// __MIDL___MIDL_itf_AcSmComponents_0000_0012_0001
